[snowflake]
account = "THCTWUU.IZA61992"
user = "JULIAN_KOIDE"
password = "@yvWGH.X.KwtxqP4UHNwEGTGrz!nKu!7V*_rN!BUgoFR4WE9kcM_.d9cgjxsWk@KyL78Phk8QmypyCa9bwkHCyC_EkGZio!z2Ujy"
role = "ACCOUNTADMIN"
warehouse = "AMAZON_REVIEW_DB"
database = "PUBLIC"
schema = "TABLES"
